### PR TITLE
Manual test key validation

### PR DESCRIPTION
**Pull request by enkhalifapro**

### CODE REVIEW

**Review by ajinkyan83 — APPROVED** [review]
/lgtm

**Comment by ajinkyan83** [comment]
@lukaszgryglicki As the auth0 token endpoint env var value had to be changed. I will share the updated secret files for both test & prod on slack.

**Comment by lukaszgryglicki** [comment]
Do we have new auth0 secrets?

**Comment by ajinkyan83** [comment]
> Do we have new auth0 secrets?

Yes, I shared on slack for `test` enviroment

**Pull request merged**
